### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by Faerbit** [jhedev/campus#1]
The encoding of the german umlauts are not working.

**Comment by jhedev** [comment]
Where do you experience this problem? If I do a simple `curl` I can't see any problems...

**Comment by Faerbit** [comment]
![screenshot_2015-04-08-13-38-23](https://cloud.githubusercontent.com/assets/4265838/7050587/b976af98-de22-11e4-976f-d6ecc87848d4.png)

**Comment by jhedev** [comment]
I've changed the `Content-Type` header in the latest version. I hope this helps. Could you try it?

**Comment by Faerbit** [comment]
This solved the problem, thanks.

**Comment by jhedev** [comment]
Great!
